# MTR 2040 Lab 2
## Name: (your name here)
## Date: (insert date here)

The main purpose of this lab is to introduce students to the basic fundamentals of Python. Topics include basic arithmitic, variables and variable assignment, and data structures. Lets start with some basic arithmitic.

### Importing libraries / packages

There are many extremely useful libraries people have developed to aid in scientific analysis (or any functionality). Since these libraries are not a part of "base" Python, we need to install them and then explicity import them. The packages have already been installed for you, but we still need to import them.

For this lab we'll be exploring the Numpy (numerical Python) library.

to import an installed library use the **import \<library_name>**

The **as** \<your alias> is a common convienence to use an abbriviation for the library 

The period after a library means you are importing a specific funciton / class / method from the library and not the entire package. So for the matplotlib library, we are importing the pyplot functionality and setting it to the alias **'plt'** (for plot). 

It is most common to import your libraries at the top of the program, although it's not necessary as long as it is imported before it is called (remember code is read line by line starting at the top). 

In [63]:
import numpy as np

### Basic Numpy

Numpy has a specific data type we have not discussed yet, arrays. They are very similar to lists (in fact they are internally comprised of lists) and are indexed the same way. The main advantage of arrays is that you can perform complex mathematical / statistical operations on every element of the array in a fast way. It also allows for easy reshaping of n-dimentional space (such as a 3D array with x, y and z coordinates) to make computation easier and more tractable. The [documentation of numpy](https://numpy.org/doc/stable/user/absolute_beginners.html) is clean and quite extensive. 

You can also use numpy's mathematical operations on some of the datatypes you already know, like lists and tuples. To use a funciton within the numpy package, you start with the **np.\<function_name>** Let's try it.

In [64]:
temperatures = [11, 12, 34, 57, 99]
dewpoints = [9, 9, 22, 51, 45]
np.mean(temperatures) # calculate the mean of the temperature list

42.6

There are A LOT of numpy funcitons, so don't hesitate to Google them. You'll quickly memorize some of the most common ones, such as the basic statistics (mean, median, max, min, ...). 

In [65]:
print(np.min(temperatures))
print(np.max(temperatures))

11
99


So far, all the fuctions we have used have only taken a single argument. However, functions can take many arguments is the function is designed that way. The **np.quantile** function is one such example: it needs the first argument to be the object to operate on, and the second argument to be the value for the quantile to calculate. Take a look at the numpy.quantile [documentation](https://numpy.org/doc/stable/reference/generated/numpy.quantile.html).  

Note that from the documentation, the quantile needs to be a value from 0 - 100. 

In [66]:
print("The 30th percentile of our temperature list is: ", np.percentile(temperatures, 30))

The 30th percentile of our temperature list is:  16.4


Element-wise mathematical operations don't work on raw lists, but do on numpy arrays (this is the main functionality of numpy).

In [67]:
temp_dew_diff = temperatures - dewpoints # errors because both are lists

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [68]:
 # works if converted to arrays, output is of type 'array'
temp_dew_diff = np.array(temperatures) - np.array(dewpoints)
temp_dew_diff

array([ 2,  3, 12,  6, 54])

In [69]:
# is indexed the same way as a list
temp_dew_diff[2:] # start at the 2nd index (3rd element) and get the remaining values

array([12,  6, 54])

In [70]:
# you can also use a single value to be mathematically applied to every element
temp_dew_diff - 1 # subtracts 1 from every element of the array

array([ 1,  2, 11,  5, 53])

### Flow control

Controlling the "flow" of operations in Python becomes increasingly critical as programs become more complex. There are many ways in which you can do this, but they are often in the form of conditionals such as **if** statements and **for** loops.

**Indentation matters** in python, and often does not matter in other languages, specifically for flow control. For example, after an **if** statement or **for** loop is initiated, all code within that statement **must be indented with a tab** (or 4 spaces).

Three common flow operators (conditions) are '<' (less than), '>' (greater than) and '==' (equal to). Notice the **double** equals sign. The '==' denotes that it is **checking for equality**, whereas '=' tries to assign a value to a variable.

Control statements need a colon at the end of the line to denote where it begins.

In [71]:
denver_temp_f = 23.4
if denver_temp_f > 25:
    print(denver_temp_f) # indentation needed since it is within the control statement
    
# It fails to print since the condition was not satisfied

In [72]:
# we can evaluate the equality manually

# This is essentially asking: is this variable (denver_temp_f) greater than 25? (Can only be True or False)
denver_temp_f > 25  

# if statements only execute if the condition evaluates to True

False

In [73]:
# Double equal sigh does not assign it, but asks: is (left of the ==) equal to (right of the ==)?
denver_temp_f == 23.4

True

In [74]:
# we can add additional constraints to our condition with elif (else if) or else (anything else)

denver_temp_f = 21.4
if denver_temp_f > 25:
    print("Temperature is greater than 25 degrees.") # indentation needed since it is within the control statement
elif denver_temp_f < 25:
    print("Temperature is less than 25 degrees.")
else:    # only evaluate if neither of the other conditions evaluate to True
    print("Temperature is 25 degrees.")

Temperature is less than 25 degrees.


#### For loops

For loops are very common in programmaing and are a way to **iterate** through a list, array, etc. and then do something.

**The variable name that comes after the "for" keyword denotes a new variable that gets reassigned at each iteration of the loop** (in this case temp). The "in" key word denotes which object we want to iterate over.

In [75]:
# print each value of our temperature variable
for temp in temperatures:
    print(temp) # note the indentation

11
12
34
57
99


The following code produces the exact same output - can you understand why? If not, study this carefully - **this is fundamental to understanding for loops**.

In [76]:
for i in [0, 1, 2, 3, 4]:
    print(temperatures[i])

11
12
34
57
99


In [77]:
# print the variables of certrain indices
for temp in temperatures[1:4]:
    print(temp) # note the indentation

12
34
57


In [78]:
# let's combine a for loop and if statements
for t in temperatures:
    if t > 32: 
        print(t, "is above freezing.") # note the nested indentation
    elif t < 32:
        print(t, "is below freezing.")
    else:
        print(t, "is at the freezing temperature.") 

11 is below freezing.
12 is below freezing.
34 is above freezing.
57 is above freezing.
99 is above freezing.


Another very common built-in funciton is the **range()** function. By default, the range function will start at zero and iterate by 1 until the specified value. 

In [79]:
for i in range(10): # i is very common in programming - short for "index"
    print(i)

0
1
2
3
4
5
6
7
8
9


In [80]:
# if there are two arguments added, it will relate to "start" and "end"
for i in range(5, 10): # i is very common in programming - short for "index"
    print(i)

5
6
7
8
9


In [81]:
# if three arguments are included, the third argument would be "by" (defualt is 1)
for i in range(0, 10, 2):
    print(i)

0
2
4
6
8


### Function Creation

Funcitons are at the heart of programming. There are many built in functions that we have already used, but what if we want to do something unique that isn't included in our libraries? We create it ourself!

Custom functions are denoted with the key word **def** (define) for defining what our function will do. Functions generally have an input (argument, or more than one argument) and an output (also known as a return value). The return value is denoted with the **return** key word.

Let's make a simple function to add 100 to a value. 

In [82]:
# define a function that adds 100 to its input
def add_100(value):
    
    new_value = value + 100
    
    return new_value

We have now defined our function and named it **add_100**. All functions need to have parenthesis after the name, with the arguments inside (seperated by a comma if more than one). It then needs a colon to signal the work of the function begins, and needs to be indented like the flow control statememnts. The argument names (in this case, "value" can be named anything you like (just like a variable), except that variable can only be accessed within the function itself. Let's see if it works.

Once you define a function, it can be used anywhere in the code which is quite powerful.

In [83]:
add_100(50) # it works!

150

In [84]:
# Lets make a more useful function

def f_to_c_converter(temp_f):
    
    # convert temperature from fahrenheit to celsius
    temp_c = (temp_f - 32) * (5/9)
    return temp_c

In [85]:
f_to_c_converter(212) # seems to work!

100.0

In [86]:
# Lets put some stuff together

temps_in_celsius = [] # initate a blank list that we can append to
for i in range(len(temperatures)):
    temp_f = temperatures[i]
    temp_c = f_to_c_converter(temp_f)
    temps_in_celsius.append(temp_c)
print(temps_in_celsius)    

[-11.666666666666668, -11.11111111111111, 1.1111111111111112, 13.88888888888889, 37.22222222222222]


Let's unpack whats going on in the previous cell.
* First we declare a blank list so we can append new values (celsius temperatures)
* Second, we iterate through **the indices** of temperatures by giving the range function the length of temperatures
    * We could have iterated through the temperatures directly, but sometimes it is useful to have the indices instead of the value itself - often times you may want to keep track of the indices so you could use the index on a differnt list, for example.
* Third, We assign the temp_f variable to the current index of temperatures
* Fourth, we convert the temperature to celsius and assign it to a variable
* Lastly, we append the new celsius value to the list we had created

If this is still a little confusing, dont be worried, it takes some time for this to make intuitve sense. But know that something like this is a very common workflow - iterate, do something each iteration, save result somewhere.

That being said, for this example, we have a much simpler solution - feed our array to the function (remember math can be done on each element of an array).

In [87]:
f_to_c_converter(np.array(temperatures))

array([-11.66666667, -11.11111111,   1.11111111,  13.88888889,
        37.22222222])

## Excercises

1. Debug the following lines of code.

In [88]:
mean_temp = np.mean("21", "43", "65")

TypeError: 'str' object cannot be interpreted as an integer

In [ ]:
for x in range(5, 10):
if x >= 8: 
    print(x ** 2)

2. Create a function to convert from Kelvin to Fahrenheit and test that it works.

In [95]:
# your code here


3. Write a control flow to determine which of the 3 lists has the highest median value and print the result (there are numerous ways to accomplish this). The `np.median()` function will likely be useful.

In [90]:
x, y, z = [1, 4, 7, 9, 56, 76], [-34, 75, 0, 67, 24, 22], [5, 33, 77, 129023, -12, 20]

# your code here


4. Write a **function** to determine how many days had a low temperature less than or equal to 32 degrees, and apply it to the given array and demonstrate that it works correctly. The answer should be 9.

In [96]:
daily_low_temperatures = np.array([19, 29, 33, 34, 30, 32, 42, 40, 35, 25, 24, 19, 35, 26, 39, 21])

# Your code below

5. Write a function called `calc_mean` to calculate (return) the mean of a list (or array) of numbers without using the `np.mean()` function.  Of course we would likely never use this in practice because numpy already supports it, but it is a useful excersize to understand what some of these functions might look like "under the hood".  The `len()` function will probably come in handy here.

In [93]:
# your code below
